from __future__ import annotations
from typing import Any, Protocol
from .schemas import ProposalBatch

class ResearchAIProvider(Protocol):
    @property
    def provider_name(self) -> str: ...
    @property
    def model_name(self) -> str: ...
    @property
    def configured(self) -> bool: ...
    def generate_research_proposals(self, *, context: dict[str, Any], prompt: str, max_proposals: int) -> tuple[ProposalBatch, dict[str, Any]]: ...
    def analyze_research_context(self, *, context: dict[str, Any], prompt: str) -> dict[str, Any]: ...
    def generate_strategy_blueprint(self, *, context: dict[str, Any], prompt: str) -> tuple[dict[str, Any], dict[str, Any]]: ...
    def health_check(self) -> dict[str, Any]: ...
