"""create AI strategy evolution research tables
Revision ID: 016_ai_strategy_evolution
Revises: 015_blueprint_validations
Create Date: 2026-09-09
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="016_ai_strategy_evolution"; down_revision="015_blueprint_validations"; branch_labels=None; depends_on=None

def upgrade():
    op.create_table("ai_strategy_evolution_runs",
      sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True,server_default=sa.text("gen_random_uuid()")),
      sa.Column("source_blueprint_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("ai_strategy_blueprints.id",ondelete="CASCADE"),nullable=False),
      sa.Column("source_validation_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("blueprint_validation_runs.id",ondelete="CASCADE"),nullable=False),
      sa.Column("run_type",sa.String(48),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("generation_version",sa.String(32),nullable=False),
      sa.Column("requested_variants",sa.Integer(),nullable=False),sa.Column("generated_variants",sa.Integer(),nullable=False),sa.Column("validated_variants",sa.Integer(),nullable=False),sa.Column("rejected_variants",sa.Integer(),nullable=False),
      sa.Column("champion_before",postgresql.UUID(as_uuid=True),nullable=True),sa.Column("champion_after",postgresql.UUID(as_uuid=True),nullable=True),
      sa.Column("configuration",postgresql.JSONB(),nullable=False),sa.Column("configuration_hash",sa.String(64),nullable=False),sa.Column("warnings",postgresql.JSONB(),nullable=False),sa.Column("failure_reason",sa.Text()),
      sa.Column("started_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),
      sa.UniqueConstraint("source_blueprint_id","source_validation_id","generation_version","configuration_hash",name="uq_ai_strategy_evolution_run_scope"))
    op.create_index("ix_ai_strategy_evolution_runs_source_blueprint_id","ai_strategy_evolution_runs",["source_blueprint_id"]); op.create_index("ix_ai_strategy_evolution_runs_source_validation_id","ai_strategy_evolution_runs",["source_validation_id"]); op.create_index("ix_ai_strategy_evolution_run_filters","ai_strategy_evolution_runs",["run_type","status","created_at","id"])
    op.create_table("ai_strategy_variants",
      sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True,server_default=sa.text("gen_random_uuid()")),sa.Column("source_blueprint_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("ai_strategy_blueprints.id",ondelete="CASCADE"),nullable=False),sa.Column("parent_variant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("ai_strategy_variants.id",ondelete="SET NULL")),sa.Column("source_validation_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("blueprint_validation_runs.id",ondelete="SET NULL")),sa.Column("evolution_run_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("ai_strategy_evolution_runs.id",ondelete="SET NULL")),
      sa.Column("variant_type",sa.String(48),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("generation_method",sa.String(64),nullable=False),sa.Column("generation_version",sa.String(32),nullable=False),sa.Column("variant_name",sa.String(255),nullable=False),sa.Column("description",sa.Text(),nullable=False),
      sa.Column("symbol_scope",postgresql.JSONB(),nullable=False),sa.Column("timeframe_scope",postgresql.JSONB(),nullable=False),sa.Column("regime_scope",postgresql.JSONB(),nullable=False),sa.Column("feature_requirements",postgresql.JSONB(),nullable=False),sa.Column("indicator_requirements",postgresql.JSONB(),nullable=False),sa.Column("entry_logic",postgresql.JSONB(),nullable=False),sa.Column("exit_logic",postgresql.JSONB(),nullable=False),sa.Column("protection_logic",postgresql.JSONB(),nullable=False),sa.Column("risk_constraints",postgresql.JSONB(),nullable=False),sa.Column("parameter_values",postgresql.JSONB(),nullable=False),sa.Column("parameter_space_reference",postgresql.JSONB(),nullable=False),sa.Column("mutation_summary",postgresql.JSONB(),nullable=False),sa.Column("changed_fields",postgresql.JSONB(),nullable=False),sa.Column("evidence_summary",postgresql.JSONB(),nullable=False),sa.Column("lineage",postgresql.JSONB(),nullable=False),sa.Column("complexity",sa.String(16),nullable=False),sa.Column("estimated_parameter_combinations",sa.Integer(),nullable=False),sa.Column("configuration",postgresql.JSONB(),nullable=False),sa.Column("configuration_hash",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),
      sa.UniqueConstraint("source_blueprint_id","generation_version","configuration_hash",name="uq_ai_strategy_variant_scope"))
    for name,col in [("ix_ai_strategy_variants_source_blueprint_id","source_blueprint_id"),("ix_ai_strategy_variants_parent_variant_id","parent_variant_id"),("ix_ai_strategy_variants_source_validation_id","source_validation_id"),("ix_ai_strategy_variants_evolution_run_id","evolution_run_id")]:op.create_index(name,"ai_strategy_variants",[col])
    op.create_index("ix_ai_strategy_variant_filters","ai_strategy_variants",["variant_type","status","generation_method","complexity","created_at","id"])
    op.create_foreign_key("fk_ai_evolution_champion_before","ai_strategy_evolution_runs","ai_strategy_variants",["champion_before"],["id"],ondelete="SET NULL"); op.create_foreign_key("fk_ai_evolution_champion_after","ai_strategy_evolution_runs","ai_strategy_variants",["champion_after"],["id"],ondelete="SET NULL")
    op.create_table("champion_challenger_comparisons",
      sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True,server_default=sa.text("gen_random_uuid()")),sa.Column("source_blueprint_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("ai_strategy_blueprints.id",ondelete="CASCADE"),nullable=False),sa.Column("champion_variant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("ai_strategy_variants.id",ondelete="SET NULL")),sa.Column("champion_validation_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("blueprint_validation_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("challenger_variant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("ai_strategy_variants.id",ondelete="CASCADE"),nullable=False),sa.Column("challenger_validation_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("blueprint_validation_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("comparison_version",sa.String(32),nullable=False),sa.Column("comparison_scope",postgresql.JSONB(),nullable=False),sa.Column("configuration",postgresql.JSONB(),nullable=False),sa.Column("configuration_hash",sa.String(64),nullable=False),sa.Column("champion_metrics",postgresql.JSONB(),nullable=False),sa.Column("challenger_metrics",postgresql.JSONB(),nullable=False),sa.Column("difference_metrics",postgresql.JSONB(),nullable=False),sa.Column("performance_score_difference",sa.Numeric(12,8),nullable=False),sa.Column("stability_difference",sa.Numeric(12,8),nullable=False),sa.Column("drawdown_difference",sa.Numeric(20,8),nullable=False),sa.Column("expectancy_difference",sa.Numeric(20,8),nullable=False),sa.Column("profit_factor_difference",sa.Numeric(20,8),nullable=False),sa.Column("execution_cost_difference",sa.Numeric(20,8),nullable=False),sa.Column("overfit_risk_difference",sa.Numeric(12,8),nullable=False),sa.Column("challenger_wins",sa.Boolean(),nullable=False),sa.Column("decision",sa.String(48),nullable=False),sa.Column("decision_reasons",postgresql.JSONB(),nullable=False),sa.Column("warnings",postgresql.JSONB(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint("source_blueprint_id","challenger_variant_id","comparison_version","configuration_hash",name="uq_ai_champion_challenger_scope"))
    op.create_index("ix_ai_champion_challenger_source_blueprint_id","champion_challenger_comparisons",["source_blueprint_id"]);op.create_index("ix_ai_champion_challenger_challenger_variant_id","champion_challenger_comparisons",["challenger_variant_id"]);op.create_index("ix_ai_champion_challenger_filters","champion_challenger_comparisons",["decision","challenger_wins","created_at","id"])

def downgrade():
    op.drop_table("champion_challenger_comparisons"); op.drop_constraint("fk_ai_evolution_champion_after","ai_strategy_evolution_runs",type_="foreignkey"); op.drop_constraint("fk_ai_evolution_champion_before","ai_strategy_evolution_runs",type_="foreignkey"); op.drop_table("ai_strategy_variants"); op.drop_table("ai_strategy_evolution_runs")
