"""create strategy regime profiles and research portfolios
Revision ID: 017_strategy_matching_portfolios
Revises: 016_ai_strategy_evolution
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='017_strategy_matching_portfolios'; down_revision='016_ai_strategy_evolution'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('strategy_regime_profiles',
      sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('source_type',sa.String(16),nullable=False),
      sa.Column('blueprint_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('ai_strategy_blueprints.id',ondelete='CASCADE')),sa.Column('variant_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('ai_strategy_variants.id',ondelete='CASCADE')),
      sa.Column('profile_version',sa.String(32),nullable=False),sa.Column('symbol_scope',postgresql.JSONB(),nullable=False),sa.Column('timeframe_scope',postgresql.JSONB(),nullable=False),sa.Column('regime',sa.String(48),nullable=False),sa.Column('validation_ids',postgresql.JSONB(),nullable=False),
      sa.Column('sample_size',sa.Integer(),nullable=False),sa.Column('simulated_trade_count',sa.Integer(),nullable=False),sa.Column('expectancy',sa.Numeric(20,8),nullable=False),sa.Column('profit_factor',sa.Numeric(20,8),nullable=False),sa.Column('win_rate',sa.Numeric(12,8),nullable=False),sa.Column('max_drawdown',sa.Numeric(20,8),nullable=False),sa.Column('stability_score',sa.Numeric(12,8),nullable=False),sa.Column('data_quality_score',sa.Numeric(12,8),nullable=False),sa.Column('overfit_risk_score',sa.Numeric(12,8),nullable=False),sa.Column('execution_cost_drag',sa.Numeric(12,8),nullable=False),sa.Column('regime_score',sa.Numeric(12,8),nullable=False),sa.Column('compatibility_score',sa.Numeric(12,8),nullable=False),
      sa.Column('strengths',postgresql.JSONB(),nullable=False),sa.Column('weaknesses',postgresql.JSONB(),nullable=False),sa.Column('warnings',postgresql.JSONB(),nullable=False),sa.Column('configuration',postgresql.JSONB(),nullable=False),sa.Column('configuration_hash',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),
      sa.UniqueConstraint('source_type','blueprint_id','variant_id','regime','profile_version','configuration_hash',name='uq_strategy_regime_profile_scope'))
    op.create_index('ix_strategy_regime_profile_filters','strategy_regime_profiles',['regime','source_type','compatibility_score','created_at','id'])
    op.create_index('ix_strategy_regime_profiles_blueprint_id','strategy_regime_profiles',['blueprint_id']);op.create_index('ix_strategy_regime_profiles_variant_id','strategy_regime_profiles',['variant_id'])
    op.create_table('research_strategy_portfolios',
      sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('name',sa.String(255),nullable=False),sa.Column('portfolio_version',sa.String(32),nullable=False),sa.Column('portfolio_type',sa.String(48),nullable=False),sa.Column('status',sa.String(32),nullable=False),
      sa.Column('symbol_scope',postgresql.JSONB(),nullable=False),sa.Column('timeframe_scope',postgresql.JSONB(),nullable=False),sa.Column('regime_scope',postgresql.JSONB(),nullable=False),sa.Column('source_profile_ids',postgresql.JSONB(),nullable=False),sa.Column('source_blueprint_ids',postgresql.JSONB(),nullable=False),sa.Column('source_variant_ids',postgresql.JSONB(),nullable=False),sa.Column('source_validation_ids',postgresql.JSONB(),nullable=False),sa.Column('component_count',sa.Integer(),nullable=False),sa.Column('allocation_method',sa.String(48),nullable=False),sa.Column('allocation_weights',postgresql.JSONB(),nullable=False),sa.Column('expected_metrics',postgresql.JSONB(),nullable=False),sa.Column('diversification_metrics',postgresql.JSONB(),nullable=False),sa.Column('correlation_metrics',postgresql.JSONB(),nullable=False),sa.Column('concentration_score',sa.Numeric(12,8),nullable=False),sa.Column('robustness_score',sa.Numeric(12,8),nullable=False),sa.Column('data_quality_score',sa.Numeric(12,8),nullable=False),sa.Column('readiness_score',sa.Numeric(12,8),nullable=False),sa.Column('warnings',postgresql.JSONB(),nullable=False),sa.Column('blocking_reasons',postgresql.JSONB(),nullable=False),sa.Column('configuration',postgresql.JSONB(),nullable=False),sa.Column('configuration_hash',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint('portfolio_version','configuration_hash',name='uq_research_strategy_portfolio_scope'))
    op.create_index('ix_research_strategy_portfolio_filters','research_strategy_portfolios',['portfolio_type','status','created_at','id'])

def downgrade():
    op.drop_index('ix_research_strategy_portfolio_filters',table_name='research_strategy_portfolios');op.drop_table('research_strategy_portfolios');op.drop_index('ix_strategy_regime_profiles_variant_id',table_name='strategy_regime_profiles');op.drop_index('ix_strategy_regime_profiles_blueprint_id',table_name='strategy_regime_profiles');op.drop_index('ix_strategy_regime_profile_filters',table_name='strategy_regime_profiles');op.drop_table('strategy_regime_profiles')
