"""create demo strategy manifests, compatibility checks, and runtime releases

Revision ID: 020_demo_strategy_manifests
Revises: 019_research_monitoring
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="020_demo_strategy_manifests"; down_revision="019_research_monitoring"; branch_labels=None; depends_on=None

def upgrade():
    u=postgresql.UUID(as_uuid=True); j=postgresql.JSONB(astext_type=sa.Text())
    op.create_table("demo_strategy_manifests",
        sa.Column("id",u,primary_key=True,server_default=sa.text("gen_random_uuid()")),sa.Column("candidate_id",u,sa.ForeignKey("research_candidate_strategies.id",ondelete="RESTRICT"),nullable=False),sa.Column("promotion_evaluation_id",u,sa.ForeignKey("candidate_promotion_evaluations.id",ondelete="RESTRICT"),nullable=False),sa.Column("handoff_id",u,sa.ForeignKey("research_candidate_handoffs.id",ondelete="SET NULL")),sa.Column("source_blueprint_id",u,sa.ForeignKey("ai_strategy_blueprints.id",ondelete="SET NULL")),sa.Column("source_variant_id",u,sa.ForeignKey("ai_strategy_variants.id",ondelete="SET NULL")),sa.Column("source_validation_id",u,sa.ForeignKey("blueprint_validation_runs.id",ondelete="SET NULL")),sa.Column("shadow_session_id",u,sa.ForeignKey("shadow_research_sessions.id",ondelete="SET NULL")),
        sa.Column("manifest_version",sa.String(32),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("strategy_name",sa.String(255),nullable=False),sa.Column("strategy_version",sa.String(64),nullable=False),sa.Column("symbol_scope",j,nullable=False),sa.Column("timeframe_scope",j,nullable=False),sa.Column("regime_scope",j,nullable=False),sa.Column("feature_requirements",j,nullable=False),sa.Column("indicator_requirements",j,nullable=False),sa.Column("entry_logic",j,nullable=False),sa.Column("exit_logic",j,nullable=False),sa.Column("protection_logic",j,nullable=False),sa.Column("parameter_values",j,nullable=False),sa.Column("risk_constraints",j,nullable=False),sa.Column("strategy_protocol_config",j,nullable=False),sa.Column("validation_summary",j,nullable=False),sa.Column("shadow_summary",j,nullable=False),sa.Column("governance_summary",j,nullable=False),sa.Column("runtime_requirements",j,nullable=False),sa.Column("runtime_compatibility",j,nullable=False),sa.Column("warnings",j,nullable=False),sa.Column("blocking_reasons",j,nullable=False),sa.Column("configuration",j,nullable=False),sa.Column("configuration_hash",sa.String(64),nullable=False),sa.Column("supersedes_manifest_id",u,sa.ForeignKey("demo_strategy_manifests.id",ondelete="SET NULL")),sa.Column("compiled_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint("candidate_id","manifest_version","configuration_hash",name="uq_demo_strategy_manifest_scope"))
    op.create_index("ix_demo_strategy_manifest_filters","demo_strategy_manifests",["candidate_id","status","compiled_at","id"])
    op.create_table("strategy_runtime_compatibility_checks",
        sa.Column("id",u,primary_key=True,server_default=sa.text("gen_random_uuid()")),sa.Column("manifest_id",u,sa.ForeignKey("demo_strategy_manifests.id",ondelete="CASCADE"),nullable=False),sa.Column("check_version",sa.String(32),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("strategy_protocol_compatible",sa.Boolean(),nullable=False),sa.Column("feature_compatible",sa.Boolean(),nullable=False),sa.Column("indicator_compatible",sa.Boolean(),nullable=False),sa.Column("timeframe_compatible",sa.Boolean(),nullable=False),sa.Column("market_data_compatible",sa.Boolean(),nullable=False),sa.Column("protection_compatible",sa.Boolean(),nullable=False),sa.Column("risk_boundary_compatible",sa.Boolean(),nullable=False),sa.Column("deterministic_logic_compatible",sa.Boolean(),nullable=False),sa.Column("overall_score",sa.Numeric(12,8),nullable=False),sa.Column("checks",j,nullable=False),sa.Column("warnings",j,nullable=False),sa.Column("blocking_reasons",j,nullable=False),sa.Column("configuration",j,nullable=False),sa.Column("configuration_hash",sa.String(64),nullable=False),sa.Column("checked_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("manifest_id","check_version","configuration_hash",name="uq_strategy_runtime_compatibility_scope"))
    op.create_index("ix_strategy_runtime_compatibility_manifest","strategy_runtime_compatibility_checks",["manifest_id","checked_at","id"])
    op.create_table("demo_runtime_releases",
        sa.Column("id",u,primary_key=True,server_default=sa.text("gen_random_uuid()")),sa.Column("manifest_id",u,sa.ForeignKey("demo_strategy_manifests.id",ondelete="RESTRICT"),nullable=False),sa.Column("candidate_id",u,sa.ForeignKey("research_candidate_strategies.id",ondelete="RESTRICT"),nullable=False),sa.Column("compatibility_check_id",u,sa.ForeignKey("strategy_runtime_compatibility_checks.id",ondelete="RESTRICT"),nullable=False),sa.Column("release_version",sa.String(32),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("release_notes",j,nullable=False),sa.Column("governance_snapshot",j,nullable=False),sa.Column("safety_snapshot",j,nullable=False),sa.Column("configuration",j,nullable=False),sa.Column("configuration_hash",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("revoked_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("manifest_id","release_version","configuration_hash",name="uq_demo_runtime_release_scope"))
    op.create_index("ix_demo_runtime_release_filters","demo_runtime_releases",["candidate_id","status","created_at","id"])

def downgrade():
    op.drop_table("demo_runtime_releases");op.drop_table("strategy_runtime_compatibility_checks");op.drop_table("demo_strategy_manifests")
